# Generated by Django 4.2.9 on 2024-01-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/static/images/placeholder.jpg', null=True, upload_to='profile_pics/')),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address_town', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address_county', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address_eircode', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
