# Generated by Django 4.2.9 on 2024-01-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email_address_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
